### ISSUE TITLE
Access token error with Pleroma Oauth2

### ISSUE THREAD

**Issue by Salmon-Bard** [agates/peertube-plugin-auth-oauth2-mastodon#1]
I'm trying to use Oauth2 from Pleroma provider to login to Peertube but I'm facing the following issue where Access token  
is not handled correctly

`error[2/3/2021, 1:42:44 AM] Access token error.
{
  "err": {
    "stack": "TypeError: Cannot read property 'body' of null\n    at new Request (/var/www/peertube/storage/plugins/node_modules/servie/dist/node.js:148:30)\n    at Object.fetch (/var/www/peertube/storage/plugins/node_modules/popsicle/dist/common.js:14:15)\n    at /var/www/peertube/storage/plugins/node_modules/peertube-plugin-auth-oauth2-mastodon/main.js:88:18\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Cannot read property 'body' of null"
  }
}`

The Pelroma Oauth2 code is expecting a "grant_type=authorization_code" when sending authorization request but it seems that this plugin is not sending it with the request. I'm not sure if that is the issue !!!

Any suggestions or guidance to troubleshoot this issue 

Thanks

**Comment by agates** [comment]
Sorry I've only just seen this -- is it configured to use the Authorization header or the URL parameter?

**Comment by chizutan5** [comment]
I have the same problem, this is the configuration: 
![image](https://user-images.githubusercontent.com/68605288/200689364-92d0fa12-333a-4420-b95f-84f5cd07cf24.png)

Peertube error:
{"err":{"stack":"Error: HTTP status 404\n    at /mnt/data1/peertube/storage/plugins/node_modules/client-oauth2/src/client-oauth2.js:283:25\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","message":"HTTP status 404","status":404,"body":"{\"errors\":{\"detail\":\"Page not found\"}}","code":"ESTATUS"},"level":"error","message":"Access token error.","label":"v.y********:443 peertube-plugin-auth-oauth2-mastodon","timestamp":"2022-11-08T22:19:38.963Z"}

All it does is throw me back to the login page but it's completely blank and will not show up without a cache clearing reload.
